# Generated by Django 4.2.3 on 2023-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('frequency', models.TextField(max_length=1000)),
                ('indication', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
