# Generated by Django 4.2.3 on 2023-07-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.TextField(max_length=100)),
                ('brand_name', models.TextField(max_length=100)),
                ('uses', models.TextField(max_length=5000)),
                ('how_it_works', models.TextField(max_length=5000)),
                ('side_effects', models.TextField(max_length=5000)),
                ('counseling_points', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
    ]
