# Generated by Django 4.2.3 on 2023-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medication',
            name='indication',
            field=models.CharField(max_length=1000),
        ),
    ]
